Add .sum extension
Samsung/CredSweeper pull request #186
Opened 2022-08-10 09:25 UTC by csh519

There are some FP cases from .sum files.
.sum file is checksum file of golang, so it can be excluded from scanning.

2022-08-10 09:59 UTC, babenek approved these changes
ok. ```.sum ``` should be skipped

2022-08-10 09:59 UTC, babenek commented on credsweeper/secret/config.json
> +}
too many extra changes :(

2022-08-10 10:00 UTC, babenek commented on credsweeper/secret/config.json
> +}
```suggestion
}

```

2022-08-10 10:00 UTC, babenek requested changes
please, fix line ending

2022-08-10 10:02 UTC, babenek approved these changes
LGTM

2022-08-10 10:53 UTC, kmnls approved these changes

2022-08-10 11:55 UTC, merged

2022-08-11 10:15 UTC, babenek commented
@csh519 , sorry, i wanted merge the changes from develop to resolve conflicts in next PRs.
Will merge from your fork next time