Use built-in data instead file distribution
Samsung/CredSweeper pull request #187
Opened 2022-08-10 10:13 UTC by babenek

- use built-in data instead file distribution.

2022-08-11 12:06 UTC, meanrin requested changes
Strongly oppose to this idea
`.onnx` and `.json` model files is not the python code, and should not be treated as such 
This change is akin moving `.jpg` or `.dll` files to inside the python code 
It’s just much more complicated and obscure 

Moreover, that change would make it uncomfortable to change model files in case of retrain
Currently it is relatively easy to substitute a new model if we trained one: copy-paste 2 files from train directory. But with this change it would require to rewrite python code and use additional base 64 conversion

2022-08-11 14:47 UTC, babenek commented
@meanrin Ok, let the ml model data left as is.
I'm having intend to move some config to python code to export for user modification and import. #170 
I hope, you have no objection?

2022-08-19 10:24 UTC, meanrin approved these changes
LGTM
However, I think we need to add more comments to tests as they might be less obvious with each new functionality added

2022-08-19 10:24 UTC, meanrin commented on credsweeper/utils/util.py
> +    def json_load(file_path: str, encoding=DEFAULT_ENCODING) -> Any:
Ooo, fancy
Thank you for adding those functions

2022-08-19 10:24 UTC, meanrin commented on tests/utils/test_util.py
> +    def test_json_dump_p(self):
Imo it's a bit unclear what is being tested here
Docstring comments might be a nice idea
please conciser adding them with that or different PR

2022-08-19 11:40 UTC, kmnls approved these changes

2022-08-19 11:53 UTC, merged