Separate function for future reusing
Samsung/CredSweeper pull request #470
Opened 2023-12-03 11:39 UTC by babenek

## Description

Please include a summary of the change and which is fixed.

- base64 decode function is extracted for reuse
- applied padding auto augmentation for base64 JWT which may be without padding
- ASN1 size check applied for small size case

## How has this been tested?

Please describe the tests that you ran to verify your changes.

- [x] UnitTest
- [x] Benchmark

2023-12-04 11:40 UTC, Yullia approved these changes

2023-12-04 16:24 UTC, kmnls commented on credsweeper/utils/util.py
> +        if urlsafe_detect and '-' in value or '_' in value:
```suggestion
        if urlsafe_detect and ('-' in value or '_' in value):
```
AND has higher precedence then OR

2023-12-04 16:25 UTC, kmnls requested changes
See comment

2023-12-05 08:41 UTC, babenek commented
> See comment

Thank you for review. The issue was fixed.

2023-12-05 09:40 UTC, xDizzix approved these changes
+

2023-12-05 09:49 UTC, kmnls approved these changes
Agree

2023-12-05 09:50 UTC, merged