Confidence of rule
Samsung/CredSweeper pull request #500
Opened 2024-01-31 14:07 UTC by babenek

## Description

Please include a summary of the change and which is fixed.

- Add confidence for rule which may be used in Candidate
- Fix url password detection in sources with quotes

## How has this been tested?

Please describe the tests that you ran to verify your changes.

- [x] UnitTest
- [ ] Benchmark

2024-02-01 07:45 UTC, kmnls submitted a review, later dismissed
Agree

2024-02-02 04:12 UTC, csh519 requested changes
Please check my mail.

2024-02-12 10:57 UTC, babenek reviewed
@csh519 can you apply?

2024-02-12 10:57 UTC, babenek commented on credsweeper/rules/config.yaml
> +  confidence: strong
```suggestion
```

2024-02-12 10:57 UTC, babenek commented on credsweeper/rules/config.yaml
> +  confidence: strong
```suggestion
```

2024-02-13 08:14 UTC, csh519 commented
Please add confidence level to all rules on `rules/config.yaml` file.

2024-02-13 09:39 UTC, csh519 submitted a review, later dismissed
Thank you for adding `Confidence` field.
All `Confidence` levels are discussed internally.

LGTM :+1:

2024-02-13 11:17 UTC, Yullia submitted a review, later dismissed

2024-02-13 11:59 UTC, kmnls approved these changes

2024-02-13 12:50 UTC, xDizzix commented on credsweeper/common/constants.py
> +    def get(severity: Union[str, "Confidence"]) -> Optional["Confidence"]:
```suggestion
    def get(confidence: Union[str, "Confidence"]) -> Optional["Confidence"]:
```

2024-02-13 12:50 UTC, xDizzix commented on credsweeper/common/constants.py
> +            value = getattr(Confidence, severity.strip().upper(), None)
```suggestion
        if isinstance(confidence, Confidence):
            return confidence
        if isinstance(confidence, str):
            value = getattr(Confidence, confidence.strip().upper(), None)
```

2024-02-13 13:33 UTC, xDizzix approved these changes
+

2024-02-13 13:40 UTC, iuriimet approved these changes

2024-02-13 14:06 UTC, merged