jwt check
Samsung/CredSweeper pull request #549
Opened 2024-04-29 17:06 UTC by babenek

## Description

Please include a summary of the change and which is fixed.

- Add A
- Fix B

## How has this been tested?

Please describe the tests that you ran to verify your changes.

- [ ] UnitTest
- [ ] Benchmark

2024-04-30 16:02 UTC, babenek reviewed
TODO: rollback after https://github.com/Samsung/CredData/pull/122

2024-04-30 16:02 UTC, babenek commented on .github/workflows/benchmark.yml
> +          ref: jwt
```suggestion
          repository: Samsung/CredData
```

2024-04-30 16:02 UTC, babenek commented on .github/workflows/benchmark.yml
> +          ref: jwt
```suggestion
          repository: Samsung/CredData
```

2024-04-30 16:02 UTC, babenek commented on .github/workflows/benchmark.yml
> +          ref: jwt
```suggestion
          repository: Samsung/CredData
```

2024-04-30 16:02 UTC, babenek commented on .github/workflows/benchmark.yml
> +          ref: jwt
```suggestion
          repository: Samsung/CredData
```

2024-05-02 06:53 UTC, kmnls submitted a review, later dismissed
Agree, seems ok

2024-05-02 07:51 UTC, xDizzix requested changes
The rule is too loose

2024-05-02 07:51 UTC, xDizzix commented on credsweeper/rules/config.yaml
> +  confidence: strong
I think it a controversial statement that the JSON encoded in base64 is a security threat

2024-05-02 07:51 UTC, xDizzix commented on credsweeper/filters/value_jwt_check.py
> +    def run(self, line_data: LineData, target: AnalysisTarget) -> bool:
The checker is very loose. It must be more strict, at least check the inner structure for the presence of some security-related keywords.

2024-05-02 07:51 UTC, xDizzix commented on experiment/src/entropy_test.py
> +# 33 = (4.57601357276539, 0.13672208599146715)
Please describe what is this data for

2024-05-08 11:54 UTC, Yullia approved these changes
Approved

2024-08-07 09:41 UTC, Yullia approved these changes

2024-08-07 10:11 UTC, xDizzix approved these changes

2024-08-07 10:17 UTC, merged