Subhashtext
Samsung/CredSweeper pull request #582
Opened 2024-07-14 05:46 UTC by babenek

## Description

Please include a summary of the change and which is fixed.

- Add A
- Fix B

## How has this been tested?

Please describe the tests that you ran to verify your changes.

- [ ] UnitTest
- [ ] Benchmark

2024-07-16 10:40 UTC, xDizzix requested changes
Implementation is rather tangled. The solution for a quite rare task is not worth the overcomplication of this part of the code.

2024-08-14 06:58 UTC, babenek commented on tests/test_main.py
> +        content_provider: AbstractProvider = FilesProvider([SAMPLES_PATH / "ttt.oracle"])
```suggestion
        content_provider: AbstractProvider = FilesProvider([SAMPLES_PATH / "binary.yaml"])
```

2024-08-14 08:51 UTC, babenek commented
> Implementation is rather tangled. The solution for a quite rare task is not worth the overcomplication of this part of the code.

--subtext reduces json report size of unfiltered data for ML train.
--hashes allows use report of sensetive data for BM without data disclosure

2024-08-14 10:43 UTC, xDizzix approved these changes

2024-08-14 11:01 UTC, iuriimet approved these changes

2024-08-14 11:08 UTC, merged